pyconkr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from pyconkr.views import TutorialProposalCreate, TutorialProposalDetail, \
    TutorialProposalUpdate, TutorialProposalList, tutorial_join,\
    SprintProposalCreate, SprintProposalDetail, sprint_join, SprintProposalUpdate

from .views import index, schedule, robots
from .views import RoomDetail
from .views import AnnouncementList, AnnouncementDetail
from .views import SpeakerList, SpeakerDetail, SpeakerUpdate
from .views import SponsorList, SponsorDetail, PatronList
from .views import ProgramList, ProgramDetail, ProgramUpdate, PreferenceList
from .views import ProposalCreate, ProposalUpdate, ProposalDetail
from .views import ProfileDetail, ProfileUpdate
from .views import login, login_req, login_mailsent, logout

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^robots.txt$', robots, name='robots'),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    # url(r'.*', TemplateView.as_view(template_name='teaser/index.html')),
    url(r'^$', index, name='index'),
    url(r'^room/(?P<pk>\d+)$',
        RoomDetail.as_view(), name='room'),
    url(r'^about/announcements/$',
        AnnouncementList.as_view(), name='announcements'),
    url(r'^about/announcement/(?P<pk>\d+)$',
        AnnouncementDetail.as_view(), name='announcement'),
    url(r'^about/sponsor/$',
        SponsorList.as_view(), name='sponsors'),
    url(r'^about/patron/$',
        PatronList.as_view(), name='patrons'),
    url(r'^about/sponsor/(?P<slug>[\w|-]+)$',
        SponsorDetail.as_view(), name='sponsor'),
    url(r'^programs?/list/$',
        ProgramList.as_view(), name='programs'),
    url(r'^programs?/preference/$',
        login_required(PreferenceList.as_view()), name='program_preference'),
    url(r'^program/(?P<pk>\d+)$',
        ProgramDetail.as_view(), name='program'),
    url(r'^program/(?P<pk>\d+)/edit$',
        ProgramUpdate.as_view(), name='program_edit'),
    url(r'^programs?/speakers?/$',
        SpeakerList.as_view(), name='speakers'),
    url(r'^programs?/speakers?/(?P<slug>\w+)$',
        SpeakerDetail.as_view(), name='speaker'),
    url(r'^programs?/speakers?/(?P<slug>\w+)/edit$',
        SpeakerUpdate.as_view(), name='speaker_edit'),
    url(r'^programs?/schedule/$',
        schedule, name='schedule'),
    url(r'^programs?/tutorials/$',
        TutorialProposalList.as_view(), name='tutorials'),
    url(r'^programs?/tutorial/(?P<pk>\d+)$',
        TutorialProposalDetail.as_view(), name='tutorial'),
    url(r'^programs?/tutorial/(?P<pk>\d+)/join/$',
        login_required(tutorial_join), name='tutorial-join'),
    url(r'^programs?/sprint/(?P<pk>\d+)$',
        SprintProposalDetail.as_view(), name='sprint'),
    url(r'^programs?/sprint/(?P<pk>\d+)/join/$',
        login_required(sprint_join), name='sprint-join'),
    url(r'^cfp/propose/$',
        login_required(ProposalCreate.as_view()), name='propose'),
    url(r'^cfp/tutorial-propose/$',
        login_required(TutorialProposalCreate.as_view()), name='tutorial-propose'),
    url(r'^profile/proposal/$',
        login_required(ProposalDetail.as_view()), name='proposal'),
    url(r'^cfp/sprint-propose/$',
        login_required(SprintProposalCreate.as_view()), name='sprint-propose'),
    url(r'^profile/proposal/edit$',
        login_required(ProposalUpdate.as_view()), name='proposal-update'),
    url(r'^profile/tutorial-proposal/edit$',
        login_required(TutorialProposalUpdate.as_view()), name='tutorial-proposal-update'),
    url(r'^profile/sprint-proposal/edit$',
        login_required(SprintProposalUpdate.as_view()), name='sprint-proposal-update'),
    url(r'^profile$',
        login_required(ProfileDetail.as_view()), name='profile'),
    url(r'^profile/edit$',
        login_required(ProfileUpdate.as_view()), name='profile_edit'),

    url(r'^login/$', login, name='login'),
    url(r'^login/req/(?P<token>[a-z0-9\-]+)$', login_req, name='login_req'),
    url(r'^login/mailsent/$', login_mailsent, name='login_mailsent'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^registration/', include('registration.urls')),

    # for flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^(?P<url>.*/)$', views.flatpage, name='flatpage'),

    prefix_default_language=False
)

# for development
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls')),
    ]

pyconkr/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import date as _date
from django.utils.translation import ugettext_lazy as _
from sorl.thumbnail import ImageField as SorlImageField
from jsonfield import JSONField
from uuid import uuid4
from constance import config

class Room(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=255, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('room', args=[self.id])

    def __str__(self):
        return self.name


class ProgramDate(models.Model):
    day = models.DateField()

    def __str__(self):
        return _date(self.day, "Y-m-d (D)")


class ProgramTime(models.Model):
    name = models.CharField(max_length=100)
    begin = models.TimeField()
    end = models.TimeField()
    day = models.ForeignKey(ProgramDate, null=True, blank=True)

    def __meta__(self):
        ordering = ['begin']

    def __str__(self):
        return '%s - %s / %s / %s' % (self.begin, self.end, self.name, self.day)


class ProgramCategory(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    show_in_mobile = models.BooleanField(default=True)
    show_in_list = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class SponsorLevelManager(models.Manager):
    def get_queryset(self):
        return super(SponsorLevelManager, self).get_queryset().all().order_by('order')


class SponsorLevel(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)
    desc = models.TextField(null=True, blank=True)
    order = models.IntegerField(default=1)

    objects = SponsorLevelManager()

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='sponsor', null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    level = models.ForeignKey(SponsorLevel, null=True, blank=True)

    class Meta:
        ordering = ['id']

    def get_absolute_url(self):
        return reverse('sponsor', args=[self.slug])

    def __str__(self):
        return self.name


class Speaker(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, db_index=True)
    organization = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=255, db_index=True,
                              null=True, blank=True)
    image = models.ImageField(upload_to='speaker', null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    info = JSONField(blank=True, help_text=_('help-text-for-speaker-info'))

    class Meta:
        ordering = ['name']

    def get_badges(self, size_class=""):
        badge = \
            '<a class="btn btn-social btn-social-default {} btn-{}" href="{}" target="_blank">' \
            '<i class="fa fa-external-link fa-{}"></i>{}</a>'
        fa_replacement = {
            "homepage": "home",
            "blog": "pencil",
        }
        result = []
        if type(self.info) == str:
            return '<div class="badges">{}</div>'.format(' '.join(result))
        
        for site, url in self.info.items():
            result.append(badge.format(
                size_class,
                site, url,
                fa_replacement.get(site, site), site.capitalize()
            ))
        return '<div class="badges">{}</div>'.format(' '.join(result))

    def get_badges_xs(self):
        return self.get_badges("btn-xs")

    def get_absolute_url(self):
        return reverse('speaker', args=[self.slug])

    def get_image_url(self):
        if self.image:
            return self.image.url

        return static('image/anonymous.png')

    def __str__(self):
        return '%s / %s' % (self.name, self.slug)


class Program(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    brief = models.TextField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    slide_url = models.CharField(max_length=255, null=True, blank=True)
    pdf_url = models.CharField(max_length=255, null=True, blank=True)
    video_url = models.CharField(max_length=255, null=True, blank=True)
    speakers = models.ManyToManyField(Speaker, blank=True)
    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),
                                      ('I', _('Intermediate')),
                                      ('E', _('Experienced')),
                                  ), default='B')

    duration = models.CharField(max_length=1,
                                choices=(
                                    ('S', _('25 mins')),
                                    ('L', _('40 mins')),
                                ), default='S')

    language = models.CharField(max_length=1,
                                choices=(
                                    ('E', _('English')),
                                    ('K', _('Korean')),
                                ), default='E')

    date = models.ForeignKey(ProgramDate, null=True, blank=True)
    rooms = models.ManyToManyField(Room, blank=True)
    times = models.ManyToManyField(ProgramTime, blank=True)
    category = models.ForeignKey(ProgramCategory, null=True, blank=True)

    is_recordable = models.BooleanField(default=True)
    is_breaktime = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('program', args=[self.id])

    def room(self):
        rooms = self.rooms.all()

        if rooms.count() == Room.objects.all().count():
            return ''

        return ', '.join([_.name for _ in self.rooms.all()])

    def get_slide_url_by_begin_time(self):
        from datetime import datetime

        if not config.SHOW_SLIDE_DATA:
            return None

        time = self.times.first()

        if not time:
            return None

        opendate = datetime(year=time.day.day.year, month=time.day.day.month, day=time.day.day.day, hour=time.begin.hour,
                            minute=time.begin.minute)
        if datetime.now() >= opendate:
            return self.slide_url
        else:
            return None

    def begin_time(self):
        return self.times.all()[0].begin.strftime("%H:%M")

    def get_speakers(self):
        return ', '.join([u'{}({})'.format(_.name, _.email) for _ in self.speakers.all()])
    get_speakers.short_description = u'Speakers'

    def get_times(self):
        times = self.times.all()

        if times:
            return '%s - %s' % (times[0].begin.strftime("%H:%M"),
                                times[len(times) - 1].end.strftime("%H:%M"))
        else:
            return _("Not arranged yet")

    def __str__(self):
        return self.name


class Announcement(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    desc = models.TextField(null=True, blank=True)

    announce_after = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def at(self):
        return self.announce_after if self.announce_after else self.created

    def __str__(self):
        return self.title


class EmailToken(models.Model):
    email = models.EmailField(max_length=255)
    token = models.CharField(max_length=64, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.token = str(uuid4())
        super(EmailToken, self).save(*args, **kwargs)


class Proposal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    brief = models.TextField(max_length=1000)
    desc = models.TextField(max_length=4000)
    comment = models.TextField(max_length=4000, null=True, blank=True)

    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),
                                      ('I', _('Intermediate')),
                                      ('E', _('Experienced')),
                                  ))

    duration = models.CharField(max_length=1,
                                choices=(
                                    ('S', _('25 mins')),
                                    ('L', _('40 mins')),
                                ))

    language = models.CharField(max_length=1,
                                choices=(
                                    ('E', _('English')),
                                    ('K', _('Korean')),
                                ),
                                default='E')

    def __str__(self):
        return self.title


class TutorialProposal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    brief = models.TextField(max_length=1000)
    desc = models.TextField()
    comment = models.TextField(max_length=4000, null=True, blank=True)

    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),

pyconkr/templates/banner.html
<ul class="banners">
{% for banner in banners %}
  <li class="banner">
    <a href="{{ banner.url }}">
        <img src="{{ MEDIA_URL }}{{ banner.image }}" alt="{{ banner.name }}">
    </a>
    {{ banner.desc|safe }}
  </li>
{% endfor %}
</ul>

pyconkr/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
  <title>{% block head-title %}{% trans "PyCon Korea 2017" %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=0.85">

  <!-- Opengraph tag -->
  <meta property="og:site_name" content="{% trans "PyCon Korea 2017" %}">
  <meta property="og:title" content="{% block og-title %}{% trans "PyCon Korea 2017" %}{% endblock %}">
  <meta property="og:image" content="{{ domain }}{% block og-image %}{% static "image/pyconkr-2017-cover.png" %}{% endblock %}">
  <meta property="og:url" content="{{ domain }}{{ request.path }}">
  <meta property="og:description" content="{% block og-desc %}{% trans "PyCon Korea Opengraph Description" %}{% endblock %}">

  <!-- Include basic items -->
  <link href="{% static "components/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "components/bootstrap-social/bootstrap-social.css" %}" rel="stylesheet">
  <link href="{% static "components/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "components/montserrat-webfont/css/montserrat-webfont.min.css" %}" rel="stylesheet">

  <!-- Override bootstrap css -->
  <link href="{% static "css/pyconkr.css" %}" rel="stylesheet">
  <link href="{% static "css/pyconkr-media.css" %}" rel="stylesheet">

  <!-- Google fonts -->
  <link href='//fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/earlyaccess/nanumgothic.css' rel='stylesheet' type='text/css'>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static "image/favicon.ico" %}" type="image/x-icon">
  <link rel="icon" href="{% static "image/favicon.ico" %}" type="image/x-icon">

  <!-- Scripts -->
  <!--[if lt IE 9]>
    <script src="{% static "components/html5shiv/dist/html5shiv.min.js" %}"></script>
    <script src="{% static "components/respond/dest/respond.min.js" %}"></script>
  <![endif]-->
  <script src="{% static "components/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/rgb-hsv.js" %}"></script>
  <script src="{% static "components/js-cookie/src/js.cookie.js" %}" charset="utf-8"></script>
  <script src="{% static "components/handlebars/handlebars.min.js" %}" charset="utf-8"></script>
  <script>
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  </script>
  {% block head-include %}{% endblock %}
</head>

<body>
{% block nav %}{% include "nav.html" %}{% endblock %}
{% block container %}
<div class="container">
    {% block wrap %}
    <div class="row wrap">
        <div class="col-md-9 content">
            <h1>{% block title %}{{ title }}{% endblock %}</h1>
            {% if messages %}
            {% for message in messages %}
            <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {{ base_content | safe }}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-3">
            {% include "submenu.html" %}
            {% include "banner.html" %}
        </div>
    </div>
    {% endblock %}
    {% block sponsors %}
    <hr>
    <div class="row wrap">
        <div class="col-md-12 sponsors">
        <h2>{% trans "Sponsors" %}</h2>
        {% include "sponsors.html" %}
        </div>
    </div>
    {% endblock %}
</div>
{% endblock %}

{% block script %}
{% endblock %}

{% include "footer.html" %}
{% include "ga.html" %}
{% include "facebook_script.html" %}
</body>

</html>

pyconkr/templates/disqus.html
{% load i18n %}
<h3>{% trans "Comments" %}</h3>
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'pycon-korea-2017';
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

pyconkr/templates/facebook_script.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=194162310738860";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

pyconkr/templates/footer.html
{% load staticfiles %}
{% load i18n %}
<div class="footer">
    <div class="container">
        <div class="row wrap">
            <div class="col col-sm-2 pyconkr-badge">
                <img src="{% static "image/pyconkr-badge.png" %}" alt="PyCon Korea badge">
            </div>
            <div class="col col-sm-7 credit">
                <h4>
                {% trans "PyCon Korea 2017" %}
                </h4>
                <p>
                {% trans "PyCon Korea 2017 is a product of PyCon Korea Organizing Team" %}
                </p>
                <p>
                {% trans "Powered by Django" %}
                </p>
                <p>
                  {% trans "Hosted on Naver D2" %}
                  <img class="hosting" src="{% static "image/naver-d2.png" %}" alt="Hosted on Naver D2">
                </p>
            </div>
            <div class="col col-sm-3 info">
                <h4>{% trans "Stay connected" %}</h4>
                <a class="btn btn-social-icon btn-twitter" href="https://twitter.com/pyconkr">
                    <i class="fa fa-twitter"></i>
                </a>
                <a class="btn btn-social-icon btn-facebook" href="https://facebook.com/pyconkorea">
                    <i class="fa fa-facebook"></i>
                </a>
                <a class="btn btn-social-icon btn-github" href="https://github.com/pythonkr/pyconkr-2017">
                    <i class="fa fa-github"></i>
                </a>
                <a class="btn btn-social-icon btn-flickr" href="https://www.flickr.com/photos/126829363@N08/sets/">
                    <i class="fa fa-flickr"></i>
                </a>
            </div>
        </div>
    </div>
</div>

pyconkr/templates/ga.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75675713-1', 'pycon.kr');
  ga('send', 'pageview');

</script>

pyconkr/templates/login.html
{% extends "base.html" %}
{% load socialaccount %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<h3>{% trans "Login via mail" %}</h3>
<div class="alert alert-info" role="alert">
    {% trans "We store your mail address only. Never store password or any personal information." %}
</div>
{% crispy form %}
<!--
<hr>
<h3>{% trans "Login via Social accounts" %}</h3>
<p>
    <a class="btn btn-social btn-github" href="{% provider_login_url "github" %}">
        <i class="fa fa-github"></i> {% trans "Sign in with GitHub" %}</a>
    <a class="btn btn-social btn-twitter" href="{% provider_login_url "twitter" %}">
        <i class="fa fa-twitter"></i> {% trans "Sign in with Twitter" %}</a>
</p>
-->
{% endblock %}

pyconkr/templates/login_mailsent.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>{% trans "One-time login token url was sent to your mail. Please check your mailbox." %}</p>
<p>{% trans "Login token valid for only 1 hour." %} {% trans "If you lost token mail or be lated, please login again." %}</p>
<a href="{% url "index" %}" class="btn btn-large btn-primary">{% trans "Back to home" %}</a>
{% endblock %}

pyconkr/templates/login_notvalidtoken.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>{% trans "Requested token is not found or invalid." %}</p>
<p>{% trans "If you lost token mail or be lated, please login again." %}</p>
<a href="{% url "login" %}" class="btn btn-large btn-primary">{% trans "Login" %}</a>
{% endblock %}

pyconkr/templates/sponsors.html
{% load i18n %}
<div class="sponsors">
  {% for lvl in levels %}
  <h3>{{ lvl.name }}</h3>
  <ul>
    {% for sponsor in lvl.sponsor_set.all %}
      {% if sponsor.image %}
      <li class="sponsor-{{ lvl.order }}">
        <a href="{% url "sponsor" sponsor.slug %}">
          <img src="{{ MEDIA_URL }}{{ sponsor.image }}" alt="{{ sponsor.name }}">
          {% if detail == 'True' %}
          <div class="info">
            {{ sponsor.name }}
          </div>
          {% endif %}
        </a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
  {% endfor %}
</div>

pyconkr/templates/submenu.html
<div class="submenu list-group hidden-xs hidden-sm">
{% for k, v in submenu.items %}
<a href="{{ v.path }}" class="list-group-item{% if v.active %} active{% endif %}">{{ v.title }}</a>
{% endfor %}
</div>