pyconkr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from pyconkr.views import TutorialProposalCreate, TutorialProposalDetail, \
    TutorialProposalUpdate, TutorialProposalList, tutorial_join,\
    SprintProposalCreate, SprintProposalDetail, sprint_join, SprintProposalUpdate

from .views import index, schedule, robots
from .views import RoomDetail
from .views import AnnouncementList, AnnouncementDetail
from .views import SpeakerList, SpeakerDetail, SpeakerUpdate
from .views import SponsorList, SponsorDetail, PatronList
from .views import ProgramList, ProgramDetail, ProgramUpdate, PreferenceList
from .views import ProposalCreate, ProposalUpdate, ProposalDetail
from .views import ProfileDetail, ProfileUpdate
from .views import login, login_req, login_mailsent, logout

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^robots.txt$', robots, name='robots'),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    # url(r'.*', TemplateView.as_view(template_name='teaser/index.html')),
    url(r'^$', index, name='index'),
    url(r'^room/(?P<pk>\d+)$',
        RoomDetail.as_view(), name='room'),
    url(r'^about/announcements/$',
        AnnouncementList.as_view(), name='announcements'),
    url(r'^about/announcement/(?P<pk>\d+)$',
        AnnouncementDetail.as_view(), name='announcement'),
    url(r'^about/sponsor/$',
        SponsorList.as_view(), name='sponsors'),
    url(r'^about/patron/$',
        PatronList.as_view(), name='patrons'),
    url(r'^about/sponsor/(?P<slug>[\w|-]+)$',
        SponsorDetail.as_view(), name='sponsor'),
    url(r'^programs?/list/$',
        ProgramList.as_view(), name='programs'),
    url(r'^programs?/preference/$',
        login_required(PreferenceList.as_view()), name='program_preference'),
    url(r'^program/(?P<pk>\d+)$',
        ProgramDetail.as_view(), name='program'),
    url(r'^program/(?P<pk>\d+)/edit$',
        ProgramUpdate.as_view(), name='program_edit'),
    url(r'^programs?/speakers?/$',
        SpeakerList.as_view(), name='speakers'),
    url(r'^programs?/speakers?/(?P<slug>\w+)$',
        SpeakerDetail.as_view(), name='speaker'),
    url(r'^programs?/speakers?/(?P<slug>\w+)/edit$',
        SpeakerUpdate.as_view(), name='speaker_edit'),
    url(r'^programs?/schedule/$',
        schedule, name='schedule'),
    url(r'^programs?/tutorials/$',
        TutorialProposalList.as_view(), name='tutorials'),
    url(r'^programs?/tutorial/(?P<pk>\d+)$',
        TutorialProposalDetail.as_view(), name='tutorial'),
    url(r'^programs?/tutorial/(?P<pk>\d+)/join/$',
        login_required(tutorial_join), name='tutorial-join'),
    url(r'^programs?/sprint/(?P<pk>\d+)$',
        SprintProposalDetail.as_view(), name='sprint'),
    url(r'^programs?/sprint/(?P<pk>\d+)/join/$',
        login_required(sprint_join), name='sprint-join'),
    url(r'^cfp/propose/$',
        login_required(ProposalCreate.as_view()), name='propose'),
    url(r'^cfp/tutorial-propose/$',
        login_required(TutorialProposalCreate.as_view()), name='tutorial-propose'),
    url(r'^profile/proposal/$',
        login_required(ProposalDetail.as_view()), name='proposal'),
    url(r'^cfp/sprint-propose/$',
        login_required(SprintProposalCreate.as_view()), name='sprint-propose'),
    url(r'^profile/proposal/edit$',
        login_required(ProposalUpdate.as_view()), name='proposal-update'),
    url(r'^profile/tutorial-proposal/edit$',
        login_required(TutorialProposalUpdate.as_view()), name='tutorial-proposal-update'),
    url(r'^profile/sprint-proposal/edit$',
        login_required(SprintProposalUpdate.as_view()), name='sprint-proposal-update'),
    url(r'^profile$',
        login_required(ProfileDetail.as_view()), name='profile'),
    url(r'^profile/edit$',
        login_required(ProfileUpdate.as_view()), name='profile_edit'),

    url(r'^login/$', login, name='login'),
    url(r'^login/req/(?P<token>[a-z0-9\-]+)$', login_req, name='login_req'),
    url(r'^login/mailsent/$', login_mailsent, name='login_mailsent'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^registration/', include('registration.urls')),

    # for flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^(?P<url>.*/)$', views.flatpage, name='flatpage'),

    prefix_default_language=False
)

# for development
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls')),
    ]

pyconkr/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import date as _date
from django.utils.translation import ugettext_lazy as _
from sorl.thumbnail import ImageField as SorlImageField
from jsonfield import JSONField
from uuid import uuid4
from constance import config

class Room(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=255, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('room', args=[self.id])

    def __str__(self):
        return self.name


class ProgramDate(models.Model):
    day = models.DateField()

    def __str__(self):
        return _date(self.day, "Y-m-d (D)")


class ProgramTime(models.Model):
    name = models.CharField(max_length=100)
    begin = models.TimeField()
    end = models.TimeField()
    day = models.ForeignKey(ProgramDate, null=True, blank=True)

    def __meta__(self):
        ordering = ['begin']

    def __str__(self):
        return '%s - %s / %s / %s' % (self.begin, self.end, self.name, self.day)


class ProgramCategory(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    show_in_mobile = models.BooleanField(default=True)
    show_in_list = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class SponsorLevelManager(models.Manager):
    def get_queryset(self):
        return super(SponsorLevelManager, self).get_queryset().all().order_by('order')


class SponsorLevel(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)
    desc = models.TextField(null=True, blank=True)
    order = models.IntegerField(default=1)

    objects = SponsorLevelManager()

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='sponsor', null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    level = models.ForeignKey(SponsorLevel, null=True, blank=True)

    class Meta:
        ordering = ['id']

    def get_absolute_url(self):
        return reverse('sponsor', args=[self.slug])

    def __str__(self):
        return self.name


class Speaker(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, db_index=True)
    organization = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=255, db_index=True,
                              null=True, blank=True)
    image = models.ImageField(upload_to='speaker', null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    info = JSONField(blank=True, help_text=_('help-text-for-speaker-info'))

    class Meta:
        ordering = ['name']

    def get_badges(self, size_class=""):
        badge = \
            '<a class="btn btn-social btn-social-default {} btn-{}" href="{}" target="_blank">' \
            '<i class="fa fa-external-link fa-{}"></i>{}</a>'
        fa_replacement = {
            "homepage": "home",
            "blog": "pencil",
        }
        result = []
        if type(self.info) == str:
            return '<div class="badges">{}</div>'.format(' '.join(result))
        
        for site, url in self.info.items():
            result.append(badge.format(
                size_class,
                site, url,
                fa_replacement.get(site, site), site.capitalize()
            ))
        return '<div class="badges">{}</div>'.format(' '.join(result))

    def get_badges_xs(self):
        return self.get_badges("btn-xs")

    def get_absolute_url(self):
        return reverse('speaker', args=[self.slug])

    def get_image_url(self):
        if self.image:
            return self.image.url

        return static('image/anonymous.png')

    def __str__(self):
        return '%s / %s' % (self.name, self.slug)


class Program(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    brief = models.TextField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    slide_url = models.CharField(max_length=255, null=True, blank=True)
    pdf_url = models.CharField(max_length=255, null=True, blank=True)
    video_url = models.CharField(max_length=255, null=True, blank=True)
    speakers = models.ManyToManyField(Speaker, blank=True)
    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),
                                      ('I', _('Intermediate')),
                                      ('E', _('Experienced')),
                                  ), default='B')

    duration = models.CharField(max_length=1,
                                choices=(
                                    ('S', _('25 mins')),
                                    ('L', _('40 mins')),
                                ), default='S')

    language = models.CharField(max_length=1,
                                choices=(
                                    ('E', _('English')),
                                    ('K', _('Korean')),
                                ), default='E')

    date = models.ForeignKey(ProgramDate, null=True, blank=True)
    rooms = models.ManyToManyField(Room, blank=True)
    times = models.ManyToManyField(ProgramTime, blank=True)
    category = models.ForeignKey(ProgramCategory, null=True, blank=True)

    is_recordable = models.BooleanField(default=True)
    is_breaktime = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('program', args=[self.id])

    def room(self):
        rooms = self.rooms.all()

        if rooms.count() == Room.objects.all().count():
            return ''

        return ', '.join([_.name for _ in self.rooms.all()])

    def get_slide_url_by_begin_time(self):
        from datetime import datetime

        if not config.SHOW_SLIDE_DATA:
            return None

        time = self.times.first()

        if not time:
            return None

        opendate = datetime(year=time.day.day.year, month=time.day.day.month, day=time.day.day.day, hour=time.begin.hour,
                            minute=time.begin.minute)
        if datetime.now() >= opendate:
            return self.slide_url
        else:
            return None

    def begin_time(self):
        return self.times.all()[0].begin.strftime("%H:%M")

    def get_speakers(self):
        return ', '.join([u'{}({})'.format(_.name, _.email) for _ in self.speakers.all()])
    get_speakers.short_description = u'Speakers'

    def get_times(self):
        times = self.times.all()

        if times:
            return '%s - %s' % (times[0].begin.strftime("%H:%M"),
                                times[len(times) - 1].end.strftime("%H:%M"))
        else:
            return _("Not arranged yet")

    def __str__(self):
        return self.name


class Announcement(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    desc = models.TextField(null=True, blank=True)

    announce_after = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def at(self):
        return self.announce_after if self.announce_after else self.created

    def __str__(self):
        return self.title


class EmailToken(models.Model):
    email = models.EmailField(max_length=255)
    token = models.CharField(max_length=64, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.token = str(uuid4())
        super(EmailToken, self).save(*args, **kwargs)


class Proposal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    brief = models.TextField(max_length=1000)
    desc = models.TextField(max_length=4000)
    comment = models.TextField(max_length=4000, null=True, blank=True)

    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),
                                      ('I', _('Intermediate')),
                                      ('E', _('Experienced')),
                                  ))

    duration = models.CharField(max_length=1,
                                choices=(
                                    ('S', _('25 mins')),
                                    ('L', _('40 mins')),
                                ))

    language = models.CharField(max_length=1,
                                choices=(
                                    ('E', _('English')),
                                    ('K', _('Korean')),
                                ),
                                default='E')

    def __str__(self):
        return self.title


class TutorialProposal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    brief = models.TextField(max_length=1000)
    desc = models.TextField()
    comment = models.TextField(max_length=4000, null=True, blank=True)

    difficulty = models.CharField(max_length=1,
                                  choices=(
                                      ('B', _('Beginner')),

pyconkr/templates/pyconkr/announcement_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block og-title %}{{ block.super }} {{ object.title }}{% endblock %}
{% block og-desc %}{{ object.desc|striptags|truncatechars:300 }}{% endblock %}
{% block head-title %}{{ object.title }}{% endblock %}

{% block content %}
{{ object.desc|safe }}
<p class="pull-right">{{ object.at }}</p>
<hr class="clear">
<a href="{% url "announcements" %}" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-chevron-left"></span> {% trans "Back to list" %}
</a>
{% endblock %}

pyconkr/templates/pyconkr/announcement_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {% if not object_list %}
        <p>준비중 입니다.</p>
    {% endif %}

{% for announcement in object_list %}
<dl class="announcements">
<dt>
  <h4>
    <a href="{% url "announcement" announcement.id %}">{{ announcement }}</a>
    <span class="datetime">{{ announcement.at|date:"Y-m-d" }}</span>
  </h4>
</dt>
<dd>
  {{ announcement.desc|striptags|truncatechars:300|safe }}
  <a href="{% url "announcement" announcement.id %}">
    <span class="continue">{% trans "Read more" %}</span>
  </a>
</dd>
</dl>
{% endfor %}
{% endblock %}

pyconkr/templates/pyconkr/jobfair_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% for obj in object_list %}
<dl class="jobfair well">
  <dt>
    <div class="media">
      <img class="media-object pull-right" src="{{ obj.sponsor.image.url }}" alt="sponsor image">
      <div class="media-body">
        <h2 class="media-heading">{{ obj.name }}</h2>
        {{ obj.location }}
      </div>
    </div>
  </dt>
  <hr>
  <dd>
  {{ obj.desc|safe }}
  </dd>
</dl>
{% endfor %}
{% endblock %}

pyconkr/templates/pyconkr/patron_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Patrons" %}{% endblock %}

{% block content %}
<ul class="patrons media-list">
{% for obj in object_list %}
  <li class="media">
    <div class="pull-left">
      {% thumbnail obj.user.profile.image "128x128" crop="center" as im %}
      <img class="media-patron" src="{{ im.url }}" alt="photo of {{ obj.name }}">
      {% empty %}
      <img class="media-patron" src="{% static "image/anonymous.png" %}">
      {% endthumbnail %}
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        {{ obj.name }}
        {% if obj.company %}
        / {{ obj.company }}
        {% endif %}
      </h4>
      {% if obj.user.profile.bio %}
      <div class="bio">
        {{ obj.user.profile.bio|safe }}
      </div>
      {% endif %}
    </div>
  </li>
{% endfor %}
</ul>
{% endblock %}

pyconkr/templates/pyconkr/profile_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
<div class="row profile-detail">
    {% if profile.name %}
        <div class="row">
            <div class="col-md-5">
                {% if profile.image %}
                    <img src="/media/{{ profile.image }}" width="300">
                {% else %}
                    <img src="{% static 'image/pycon_profile.png' %}" width="300">
                {% endif %}
            </div>
            <div class="col-md-7">
                <h3>
                    {{ profile.name }}
                    <a href="{% url 'profile_edit' %}"><i class="fa fa-pencil-square-o"></i></a>
                </h3>

                {% if profile.organization %}
                  <h4>{{ profile.organization }}</h4>
                {% endif %}
                {% if profile.phone %}
                  <p>{{ profile.phone }}</p>
                {% endif %}
                <div>{{ profile.bio|safe }}</div>
            </div>
        </div>

        <hr>
        <h2>{% trans 'Registration' %}</h2>
        <div>
            <h4>Ticket</h4>
            {% if is_registered %}
            <p>{% trans "Thank you for registration." %} <a href="{% url 'registration_status' %}">{% trans "Check Registration Status" %}</a> / <a href="{% url 'registration_receipt' %}">{% trans "Check Registration Receipt" %}</a> / <a href="{%  url 'certificates' %}">참석 확인증 출력</a></p>
            {% else %}
            <p>{% trans "You didn't have a ticket." %} <a href="{% url 'registration_index' %}">{% trans "Purchase a ticket" %}</a></p>
            {% endif %}

            <h4>Proposal</h4>
            {% if has_proposal %}
            <p>{% trans "Thank you for submitting." %} <a href="{% url 'proposal' %}">{% trans "Check my proposal" %}</a></p>
            {% else %}
            <p>{% trans "Please be a session speaker at PyCon." %} <a href="{% url 'propose' %}">{% trans "Submit a new proposal" %}</a></p>
            {% endif %}

            <h4>Tutorial</h4>
            {% if has_tutorial %}
            <p>{% trans "Thank you for submitting." %} <a href="{% url 'tutorial-propose' %}">{% trans "Check my proposal" %}</a></p>
            {% else %}
            <p>{% trans "Please be a tutorial speaker at PyCon." %} <a href="{% url 'tutorial-propose' %}">{% trans "Submit a new proposal" %}</a></p>
            {% endif %}

            <h4>Sprint</h4>
            {% if has_sprint %}
            <p>{% trans "Thank you for submitting." %} <a href="{% url 'sprint-propose' %}">{% trans "Check my proposal" %}</a></p>
            {% else %}
            <p>{% trans "Please be a sprint leader at PyCon." %} <a href="{% url 'sprint-propose' %}">{% trans "Submit a new proposal" %}</a></p>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endblock %}

pyconkr/templates/pyconkr/profile_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

pyconkr/templates/pyconkr/program_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head-include %}
{{ form.media }}
{% endblock %}

{% block head-title %}{{ program }}{% endblock %}
{% block title %}{{ program }}{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

pyconkr/templates/pyconkr/proposal_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row proposal-detail">
    {% if request.user.proposal %}
        <h3>
            {{ proposal.title }}
            <a href="{% url 'proposal-update' %}"><i class="fa fa-pencil-square-o"></i></a>
        </h3>
        <p>
            <span class="label label-info">{{ proposal.get_difficulty_display }}</span>
            <span class="label label-info">{{ proposal.get_duration_display }}</span>
            <span class="label label-info">{{ proposal.get_language_display }}</span>
        </p>
        <div>{{ proposal.brief|linebreaks }}</div>
        <hr>
        <div>
            <h4>{% trans "Detailed description" %}</h4>
            {{ proposal.desc|safe }}
        </div>
        <hr>
        <div>
            <h4>{% trans "Comment to reviewers" %}</h4>
            {{ proposal.comment|safe }}
        </div>

    {% endif %}
</div>
{% endblock %}

pyconkr/templates/pyconkr/proposal_form.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block head-include %}
{{ form.media }}
{% endblock %}

{% block content %}
{% if request.user.profile.is_empty %}
<div><a href="{% url 'profile_edit' %}">{% trans "Please make your profile first" %}</a></div>
{% else %}
{% crispy form %}
{% endif %}
{% endblock %}

pyconkr/templates/pyconkr/speaker_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head-include %}
{{ form.media }}
{% endblock %}

{% block head-title %}{{ speaker }}{% endblock %}
{% block title %}{{ speaker }}{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

pyconkr/templates/pyconkr/speaker_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}

{% block content %}
<ul class="speakers media-list">
{% if not object_list %}
    <p>준비중 입니다.</p>
{% endif %}
{% for speaker in object_list %}
  <li class="media">
    <a class="pull-left" href="{{ speaker.get_absolute_url }}">
      {% thumbnail speaker.image "128x128" crop="center" as im %}
      <img class="media-speakerect" src="{{ im.url }}" alt="photo of {{ speaker.name }}">
      {% empty %}
      <img class="media-speakerect" src="{% static "image/anonymous.png" %}">
      {% endthumbnail %}
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <a href="{{ speaker.get_absolute_url }}">{{ speaker.name }} / {{ speaker.slug }}</a>
        <span class="badges hidden-xs">{{ speaker.get_badges_xs|safe }}</span>
      </h4>
      <!--{{ speaker.desc|striptags|truncatechars:200|safe }}-->
      {% for program in speaker.program_set.all %}
      <a href="{{ program.get_absolute_url }}">{{ program.name }}</a>
      {% endfor %}
    </div>
  </li>
{% endfor %}
</ul>
{% endblock %}

pyconkr/templates/pyconkr/sponsor_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block head-title %}{{ block.super }} {% trans "Sponsor" %} | {{ sponsor.name }}{% endblock %}
{% block og-title %}{{ block.super }} {% trans "Sponsor" %} | {{ sponsor.name }}{% endblock %}
{% block og-image %}{{ sponsor.image.url }}{% endblock %}
{% block nav %}{% include "nav.html" with title=sponsor.name %}{% endblock %}
{% block title %}{{ sponsor.name }}{% endblock %}

{% block content %}
<div class="sponsor">
    {% if sponsor.slug != "info" %}
    <img src="{{ sponsor.image.url }}" alt="{{ sponsor.name }}">
    <ul class="list-group">
        <li class="list-group-item">
        <span class="glyphicon glyphicon-tag"></span> {{ sponsor.level }}
        </li>
        <li class="list-group-item">
        <span class="glyphicon glyphicon-share-alt"></span> {{ sponsor.url|urlize }}
        </li>
    </ul>
    {% endif %}
    <div>
        {{ sponsor.desc|safe }}
    </div>
</div>
{% endblock %}

pyconkr/templates/pyconkr/sprintproposal_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}

{% block head-title %}{{ sprint.title }} &mdash; {{ block.super }}{% endblock %}
{% block og-title %}{{ sprint.title }}{% endblock %}
{% block og-desc %}{{ sprint.project_brief }}{% endblock %}

{% block title %}
<h1>
    {{ sprint.title }}
    {% if sprint.user == request.user %}
    <a href="{% url 'sprint-proposal-update' %}" class="btn btn-primary">
        <i class="fa fa-pencil-square-o"></i> {% trans "Edit" %}
    </a>
    {% endif %}
</h1>
{% endblock %}
{% block content %}
<div class="row proposal-detail">
    <h3>{% trans "Sprinter" %}</h3>
    <h4>
        {{ sprint.user.profile.name }}
        {% if sprint.user.profile.organization %}
            <small>{{ sprint.user.profile.organization }}</small>
        {% endif %}
    </h4>
    <div>
        {{ sprint.user.profile.bio|safe }}
    </div>
    <hr>
    <div>
        <h3>{% trans "Tutorial Information" %}</h3>
        {{ sprint.comment|safe }}
    </div>
    <hr>
    <div>
        <h3>{% trans "Sprint Language" %}</h3>
        <div>{{ sprint.language|linebreaks }}</div>
        <h3>{% trans "Project brief" %}</h3>
        <div>{{ sprint.project_brief|linebreaks }}</div>
    </div>
    <hr>
    <hr>
    <div>
        <h3>{% trans "Project URL" %}</h3>
        <div>{{ sprint.project_url|linebreaks }}</div>
    </div>
    <hr>
</div>
<br>
<a href="{% url "tutorials" %}" class="btn btn-default">
    <span class="glyphicon glyphicon-chevron-left"></span> {% trans "Back to list" %}
</a>
<hr>
{% endblock %}

pyconkr/templates/pyconkr/tutorialproposal_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>Tutorials</h2>
<ul>
  {% for tutorial in tutorials %}
  <li>
    <span class="label label-info">{{ tutorial.get_type_display }}</span>
    <a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }}</a>
    {% if tutorial.id in joined_tutorials %}
    <span class="badge">{% trans "Joined" %}</span>
    {% endif %}
  </li>
  {% endfor %}
</ul>
<h2>Sprints</h2>
<ul>
  {% for sprint in sprints %}
  <li>
    <span class="label label-info">{{ sprint.get_type_display }}</span>
    <a href="{{ sprint.get_absolute_url }}">{{ sprint.title }}</a>
    {% if sprint.id in joined_sprints %}
    <span class="badge">{% trans "Joined" %}</span>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endblock %}